require 'pry'
require 'httparty'
require 'open-uri'
require 'nokogiri'
require 'tty-prompt'
require 'tty-progressbar'

require_relative '../lib/cli.rb'
require_relative '../lib/scraper.rb'
require_relative '../lib/genre.rb'
require_relative '../lib/movie.rb'
require_relative '../lib/api.rb'
require_relative '../lib/concerns/findable.rb'
require_relative '../lib/person.rb'
require_relative '../lib/star.rb'
require_relative '../lib/director.rb'