require 'pry'
require 'httparty'
require 'open-uri'
require 'nokogiri'
require 'json'

require_relative '../lib/cli.rb'
require_relative '../lib/scraper.rb'
require_relative '../lib/genre.rb'
require_relative '../lib/movie.rb'
require_relative '../lib/api.rb'